version: '3'

services:
  mariadb:
    image: mariadb:10.4.8
    environment:
      - "MYSQL_DATABASE=travelapp"
    ports:
      - 3306:3306
    volumes:
      - travelapp:/var/lib/mysql
volumes:
  travelapp:
