version: '3.1'

services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306
    network_mode: "host"
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=travelapp