version: '3'

services:
  mariadb:
    image: mariadb:10.4.8
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=123"
      - "MYSQL_DATABASE=travelapp"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
    ports:
      - 3306:3306
    volumes:
      - travelapp:/var/lib/mysql
volumes:
  travelapp:
