/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.travelapp.db;


import fi.morabotti.travelapp.db.tables.Customers;
import fi.morabotti.travelapp.db.tables.Orders;
import fi.morabotti.travelapp.db.tables.Travels;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>travelapp</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMERS_EMAIL = Indexes0.CUSTOMERS_EMAIL;
    public static final Index CUSTOMERS_PRIMARY = Indexes0.CUSTOMERS_PRIMARY;
    public static final Index ORDERS_FK_ORDERS_CUSTOMER_ID = Indexes0.ORDERS_FK_ORDERS_CUSTOMER_ID;
    public static final Index ORDERS_FK_ORDERS_TRAVEL_ID = Indexes0.ORDERS_FK_ORDERS_TRAVEL_ID;
    public static final Index ORDERS_PRIMARY = Indexes0.ORDERS_PRIMARY;
    public static final Index TRAVELS_PRIMARY = Indexes0.TRAVELS_PRIMARY;
    public static final Index TRAVELS_TRAVEL_CODE = Indexes0.TRAVELS_TRAVEL_CODE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMERS_EMAIL = Internal.createIndex("email", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.EMAIL }, true);
        public static Index CUSTOMERS_PRIMARY = Internal.createIndex("PRIMARY", Customers.CUSTOMERS, new OrderField[] { Customers.CUSTOMERS.ID }, true);
        public static Index ORDERS_FK_ORDERS_CUSTOMER_ID = Internal.createIndex("fk_orders_customer_id", Orders.ORDERS, new OrderField[] { Orders.ORDERS.CUSTOMER_ID }, false);
        public static Index ORDERS_FK_ORDERS_TRAVEL_ID = Internal.createIndex("fk_orders_travel_id", Orders.ORDERS, new OrderField[] { Orders.ORDERS.TRAVEL_ID }, false);
        public static Index ORDERS_PRIMARY = Internal.createIndex("PRIMARY", Orders.ORDERS, new OrderField[] { Orders.ORDERS.ID }, true);
        public static Index TRAVELS_PRIMARY = Internal.createIndex("PRIMARY", Travels.TRAVELS, new OrderField[] { Travels.TRAVELS.ID }, true);
        public static Index TRAVELS_TRAVEL_CODE = Internal.createIndex("travel_code", Travels.TRAVELS, new OrderField[] { Travels.TRAVELS.TRAVEL_CODE }, true);
    }
}
