/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.travelapp.db;


import fi.morabotti.travelapp.db.tables.Customers;
import fi.morabotti.travelapp.db.tables.Orders;
import fi.morabotti.travelapp.db.tables.Travels;
import fi.morabotti.travelapp.db.tables.records.CustomersRecord;
import fi.morabotti.travelapp.db.tables.records.OrdersRecord;
import fi.morabotti.travelapp.db.tables.records.TravelsRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>travelapp</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomersRecord, Long> IDENTITY_CUSTOMERS = Identities0.IDENTITY_CUSTOMERS;
    public static final Identity<OrdersRecord, Long> IDENTITY_ORDERS = Identities0.IDENTITY_ORDERS;
    public static final Identity<TravelsRecord, Long> IDENTITY_TRAVELS = Identities0.IDENTITY_TRAVELS;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_PRIMARY = UniqueKeys0.KEY_CUSTOMERS_PRIMARY;
    public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_EMAIL = UniqueKeys0.KEY_CUSTOMERS_EMAIL;
    public static final UniqueKey<OrdersRecord> KEY_ORDERS_PRIMARY = UniqueKeys0.KEY_ORDERS_PRIMARY;
    public static final UniqueKey<TravelsRecord> KEY_TRAVELS_PRIMARY = UniqueKeys0.KEY_TRAVELS_PRIMARY;
    public static final UniqueKey<TravelsRecord> KEY_TRAVELS_TRAVEL_CODE = UniqueKeys0.KEY_TRAVELS_TRAVEL_CODE;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrdersRecord, CustomersRecord> FK_ORDERS_CUSTOMER_ID = ForeignKeys0.FK_ORDERS_CUSTOMER_ID;
    public static final ForeignKey<OrdersRecord, TravelsRecord> FK_ORDERS_TRAVEL_ID = ForeignKeys0.FK_ORDERS_TRAVEL_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CustomersRecord, Long> IDENTITY_CUSTOMERS = Internal.createIdentity(Customers.CUSTOMERS, Customers.CUSTOMERS.ID);
        public static Identity<OrdersRecord, Long> IDENTITY_ORDERS = Internal.createIdentity(Orders.ORDERS, Orders.ORDERS.ID);
        public static Identity<TravelsRecord, Long> IDENTITY_TRAVELS = Internal.createIdentity(Travels.TRAVELS, Travels.TRAVELS.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_PRIMARY = Internal.createUniqueKey(Customers.CUSTOMERS, "KEY_customers_PRIMARY", Customers.CUSTOMERS.ID);
        public static final UniqueKey<CustomersRecord> KEY_CUSTOMERS_EMAIL = Internal.createUniqueKey(Customers.CUSTOMERS, "KEY_customers_email", Customers.CUSTOMERS.EMAIL);
        public static final UniqueKey<OrdersRecord> KEY_ORDERS_PRIMARY = Internal.createUniqueKey(Orders.ORDERS, "KEY_orders_PRIMARY", Orders.ORDERS.ID);
        public static final UniqueKey<TravelsRecord> KEY_TRAVELS_PRIMARY = Internal.createUniqueKey(Travels.TRAVELS, "KEY_travels_PRIMARY", Travels.TRAVELS.ID);
        public static final UniqueKey<TravelsRecord> KEY_TRAVELS_TRAVEL_CODE = Internal.createUniqueKey(Travels.TRAVELS, "KEY_travels_travel_code", Travels.TRAVELS.TRAVEL_CODE);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<OrdersRecord, CustomersRecord> FK_ORDERS_CUSTOMER_ID = Internal.createForeignKey(fi.morabotti.travelapp.db.Keys.KEY_CUSTOMERS_PRIMARY, Orders.ORDERS, "fk_orders_customer_id", Orders.ORDERS.CUSTOMER_ID);
        public static final ForeignKey<OrdersRecord, TravelsRecord> FK_ORDERS_TRAVEL_ID = Internal.createForeignKey(fi.morabotti.travelapp.db.Keys.KEY_TRAVELS_PRIMARY, Orders.ORDERS, "fk_orders_travel_id", Orders.ORDERS.TRAVEL_ID);
    }
}
