/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.travelapp.db;


import fi.morabotti.travelapp.db.tables.Customers;
import fi.morabotti.travelapp.db.tables.Orders;
import fi.morabotti.travelapp.db.tables.Travels;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in travelapp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>travelapp.customers</code>.
     */
    public static final Customers CUSTOMERS = fi.morabotti.travelapp.db.tables.Customers.CUSTOMERS;

    /**
     * The table <code>travelapp.orders</code>.
     */
    public static final Orders ORDERS = fi.morabotti.travelapp.db.tables.Orders.ORDERS;

    /**
     * The table <code>travelapp.travels</code>.
     */
    public static final Travels TRAVELS = fi.morabotti.travelapp.db.tables.Travels.TRAVELS;
}
