/*
 * This file is generated by jOOQ.
 */
package fi.morabotti.travelapp.db;


import fi.morabotti.travelapp.db.tables.Customers;
import fi.morabotti.travelapp.db.tables.Orders;
import fi.morabotti.travelapp.db.tables.Travels;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Travelapp extends SchemaImpl {

    private static final long serialVersionUID = 143068486;

    /**
     * The reference instance of <code>travelapp</code>
     */
    public static final Travelapp TRAVELAPP = new Travelapp();

    /**
     * The table <code>travelapp.customers</code>.
     */
    public final Customers CUSTOMERS = fi.morabotti.travelapp.db.tables.Customers.CUSTOMERS;

    /**
     * The table <code>travelapp.orders</code>.
     */
    public final Orders ORDERS = fi.morabotti.travelapp.db.tables.Orders.ORDERS;

    /**
     * The table <code>travelapp.travels</code>.
     */
    public final Travels TRAVELS = fi.morabotti.travelapp.db.tables.Travels.TRAVELS;

    /**
     * No further instances allowed
     */
    private Travelapp() {
        super("travelapp", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Customers.CUSTOMERS,
            Orders.ORDERS,
            Travels.TRAVELS);
    }
}
